/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vehicleregister;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author Jones Navela
 */


public class frmRegister extends javax.swing.JFrame {

    
    /**
     * Creates new form frmRegister
     */
    public frmRegister() {
        initComponents();
    }

    //Database connection to vla DB
    public boolean save(TrafficRegisterDetails trafficRegisterDetails) {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/vla","root","971126");
            //vla is the DB name, root is the username and 971126 is the password
            String query = "Insert INTO trafficregisterdetails(first_name, surname, age, address, traffic) VALUES (?,?,?,?,?)";
            PreparedStatement ps = con.prepareStatement(query);
            ps.setString(1, trafficRegisterDetails.getFirstName());
            ps.setString(2, trafficRegisterDetails.getSurname());
            ps.setInt(3, trafficRegisterDetails.getAge());
            ps.setString(4, trafficRegisterDetails.getAddress());
            ps.setString(5, trafficRegisterDetails.getTraffic());
            ps.execute();
            
            
            con.close();
       
        } catch(Exception e) {
            System.out.println(e);
        return false;
        }
    
        return true;
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        txtFirstName = new javax.swing.JTextField();
        lblFirstName = new javax.swing.JLabel();
        txtSurname = new javax.swing.JTextField();
        lblSurname = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        lblAddress = new javax.swing.JLabel();
        txtTraffic = new javax.swing.JTextField();
        lblTrafficRegisterNumber = new javax.swing.JLabel();
        lblProvince = new javax.swing.JLabel();
        rbWesternCape = new javax.swing.JRadioButton();
        rbKwaZuluNatal = new javax.swing.JRadioButton();
        rbEasternCape = new javax.swing.JRadioButton();
        rbLimpopo = new javax.swing.JRadioButton();
        rbMpumalanga = new javax.swing.JRadioButton();
        rbGauteng = new javax.swing.JRadioButton();
        rbNorthernCape = new javax.swing.JRadioButton();
        rbFreeState = new javax.swing.JRadioButton();
        rbNorthWest = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOutput = new javax.swing.JTextArea();
        btnRegister = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        txtFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstNameActionPerformed(evt);
            }
        });

        lblFirstName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblFirstName.setText("First Name");

        lblSurname.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblSurname.setText("Surname");

        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });

        lblAddress.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblAddress.setText("Address");

        txtTraffic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTrafficActionPerformed(evt);
            }
        });

        lblTrafficRegisterNumber.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTrafficRegisterNumber.setText("Traffic Register Number");

        lblProvince.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        lblProvince.setText("Province");

        rbWesternCape.setText("Western Cape");
        rbWesternCape.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbWesternCapeActionPerformed(evt);
            }
        });

        rbKwaZuluNatal.setText("KwaZulu-Natal");
        rbKwaZuluNatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbKwaZuluNatalActionPerformed(evt);
            }
        });

        rbEasternCape.setText("Eatern Cape");
        rbEasternCape.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbEasternCapeActionPerformed(evt);
            }
        });

        rbLimpopo.setText("Limpopo");
        rbLimpopo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLimpopoActionPerformed(evt);
            }
        });

        rbMpumalanga.setText("Mpumalanga");
        rbMpumalanga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMpumalangaActionPerformed(evt);
            }
        });

        rbGauteng.setText("Gauteng");
        rbGauteng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbGautengActionPerformed(evt);
            }
        });

        rbNorthernCape.setText("Northern Cape");
        rbNorthernCape.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNorthernCapeActionPerformed(evt);
            }
        });

        rbFreeState.setText("Free State");
        rbFreeState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFreeStateActionPerformed(evt);
            }
        });

        rbNorthWest.setText("North West");
        rbNorthWest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNorthWestActionPerformed(evt);
            }
        });

        txtOutput.setEditable(false);
        txtOutput.setColumns(20);
        txtOutput.setRows(5);
        jScrollPane1.setViewportView(txtOutput);

        btnRegister.setBackground(new java.awt.Color(102, 255, 102));
        btnRegister.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(51, 51, 51));
        jTextField1.setText("Vehicle Registration Form");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Age");

        btnClear.setBackground(new java.awt.Color(255, 51, 51));
        btnClear.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnClear.setText("Clear");
        btnClear.setMaximumSize(new java.awt.Dimension(85, 23));
        btnClear.setMinimumSize(new java.awt.Dimension(85, 23));
        btnClear.setPreferredSize(new java.awt.Dimension(85, 23));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegister)
                    .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProvince, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTrafficRegisterNumber)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblSurname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbEasternCape, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rbNorthernCape)
                                    .addComponent(rbWesternCape))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbKwaZuluNatal)
                                    .addComponent(rbLimpopo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rbFreeState, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbNorthWest, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rbGauteng, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rbMpumalanga)))
                            .addComponent(txtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTraffic, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(lblTrafficRegisterNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtTraffic, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbWesternCape)
                    .addComponent(rbKwaZuluNatal)
                    .addComponent(rbMpumalanga)
                    .addComponent(lblProvince, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbGauteng, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rbEasternCape)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(rbLimpopo)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbFreeState)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbNorthernCape)
                        .addComponent(rbNorthWest, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/********************************************************************************
                Only select Northern Cape
********************************************************************************/
    private void rbNorthernCapeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNorthernCapeActionPerformed
        rbWesternCape.setSelected(false);
        rbKwaZuluNatal.setSelected(false);
        rbMpumalanga.setSelected(false);
        rbEasternCape.setSelected(false);
        rbLimpopo.setSelected(false);
        rbGauteng.setSelected(false);
        rbNorthernCape.setSelected(true);
        rbFreeState.setSelected(false);
        rbNorthWest.setSelected(false);
    }//GEN-LAST:event_rbNorthernCapeActionPerformed

/********************************************************************************
                Only select Western Cape
********************************************************************************/
    private void rbWesternCapeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbWesternCapeActionPerformed
        rbWesternCape.setSelected(true);
        rbKwaZuluNatal.setSelected(false);
        rbMpumalanga.setSelected(false);
        rbEasternCape.setSelected(false);
        rbLimpopo.setSelected(false);
        rbGauteng.setSelected(false);
        rbNorthernCape.setSelected(false);
        rbFreeState.setSelected(false);
        rbNorthWest.setSelected(false);
    }//GEN-LAST:event_rbWesternCapeActionPerformed

/********************************************************************************
                Only select North West
********************************************************************************/
    private void rbNorthWestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNorthWestActionPerformed
        rbWesternCape.setSelected(false);
        rbKwaZuluNatal.setSelected(false);
        rbMpumalanga.setSelected(false);
        rbEasternCape.setSelected(false);
        rbLimpopo.setSelected(false);
        rbGauteng.setSelected(false);
        rbNorthernCape.setSelected(false);
        rbFreeState.setSelected(false);
        rbNorthWest.setSelected(true);
    }//GEN-LAST:event_rbNorthWestActionPerformed

    private void txtTrafficActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTrafficActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTrafficActionPerformed

/********************************************************************************
                Only select Limpopo
********************************************************************************/
    private void rbLimpopoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLimpopoActionPerformed
        rbWesternCape.setSelected(false);
        rbKwaZuluNatal.setSelected(false);
        rbMpumalanga.setSelected(false);
        rbEasternCape.setSelected(false);
        rbLimpopo.setSelected(true);
        rbGauteng.setSelected(false);
        rbNorthernCape.setSelected(false);
        rbFreeState.setSelected(false);
        rbNorthWest.setSelected(false);
    }//GEN-LAST:event_rbLimpopoActionPerformed

    private void txtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        TrafficRegisterDetails trafficRegisterDetails = new TrafficRegisterDetails();
        
        
        String firstName;
        firstName = txtFirstName.getText();
        trafficRegisterDetails.setFirstName(firstName);
        
        String surname;
        surname = txtSurname.getText();
        trafficRegisterDetails.setSurname(surname);
        
        int age;
        if(!txtAge.getText().isEmpty()) {
           age = Integer.parseInt(txtAge.getText());
           trafficRegisterDetails.setAge(age);
        }
        
        String address;
        address = txtAddress.getText();
        trafficRegisterDetails.setAddress(address);
        
        String traffic;
        traffic = txtTraffic.getText();
        trafficRegisterDetails.setTraffic(traffic);
       
        
        txtOutput.append("First Name:" + " "+ trafficRegisterDetails.getFirstName() + "\n");
        txtOutput.append("Surname:" + " "+ trafficRegisterDetails.getSurname() + "\n");
        txtOutput.append("Age:" + " "+ trafficRegisterDetails.getAge() + "\n");
        txtOutput.append("Address:" + " "+ trafficRegisterDetails.getAddress() + "\n");
        txtOutput.append("Traffic Number:" + " "+ trafficRegisterDetails.getTraffic() + "\n");
        
        boolean successful = save(trafficRegisterDetails);
        
        if(successful){
            txtOutput.append("Succesfuly saved to VLA Database-");
        }
        else {
            txtOutput.append("Details were not saved");
        }
        
        if(rbWesternCape.isSelected())
        {
            txtOutput.append("GHF-481-WC");
        }
        
        else if(rbKwaZuluNatal.isSelected())
        {
            txtOutput.append("CBF-710-KZN");
        }
        
        else if(rbMpumalanga.isSelected())
        {
            txtOutput.append("BLE-463-MP");
        }
        
        else if(rbEasternCape.isSelected())
        {
            txtOutput.append("ANM-205-EC");
        }
        
        else if(rbLimpopo.isSelected())
        {
            txtOutput.append("FRS-481-L");
        }
        
        else if(rbGauteng.isSelected())
        {
            txtOutput.append("PTG-906-GP");
        }
        
        else if(rbNorthernCape.isSelected())
        {
            txtOutput.append("PVD-528-NC");
        }
        
        else if(rbFreeState.isSelected())
        {
            txtOutput.append("VXQ-063-FS");
        }
        
        else if(rbNorthWest.isSelected())
        {
            txtOutput.append("JNC-730-NW");
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

/********************************************************************************
                Only select KZN
********************************************************************************/
    private void rbKwaZuluNatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbKwaZuluNatalActionPerformed
        rbWesternCape.setSelected(false);
        rbKwaZuluNatal.setSelected(true);
        rbMpumalanga.setSelected(false);
        rbEasternCape.setSelected(false);
        rbLimpopo.setSelected(false);
        rbGauteng.setSelected(false);
        rbNorthernCape.setSelected(false);
        rbFreeState.setSelected(false);
        rbNorthWest.setSelected(false);
    }//GEN-LAST:event_rbKwaZuluNatalActionPerformed

/********************************************************************************
                Only select Mpumalanga
********************************************************************************/
    private void rbMpumalangaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMpumalangaActionPerformed
        rbWesternCape.setSelected(false);
        rbKwaZuluNatal.setSelected(false);
        rbMpumalanga.setSelected(true);
        rbEasternCape.setSelected(false);
        rbLimpopo.setSelected(false);
        rbGauteng.setSelected(false);
        rbNorthernCape.setSelected(false);
        rbFreeState.setSelected(false);
        rbNorthWest.setSelected(false);
    }//GEN-LAST:event_rbMpumalangaActionPerformed

/********************************************************************************
                Only select Eastern Cape
********************************************************************************/
    private void rbEasternCapeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEasternCapeActionPerformed
        rbWesternCape.setSelected(false);
        rbKwaZuluNatal.setSelected(false);
        rbMpumalanga.setSelected(false);
        rbEasternCape.setSelected(true);
        rbLimpopo.setSelected(false);
        rbGauteng.setSelected(false);
        rbNorthernCape.setSelected(false);
        rbFreeState.setSelected(false);
        rbNorthWest.setSelected(false);
    }//GEN-LAST:event_rbEasternCapeActionPerformed

/********************************************************************************
                Only select Gauteng
********************************************************************************/
    private void rbGautengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbGautengActionPerformed
        rbWesternCape.setSelected(false);
        rbKwaZuluNatal.setSelected(false);
        rbMpumalanga.setSelected(false);
        rbEasternCape.setSelected(false);
        rbLimpopo.setSelected(false);
        rbGauteng.setSelected(true);
        rbNorthernCape.setSelected(false);
        rbFreeState.setSelected(false);
        rbNorthWest.setSelected(false);
    }//GEN-LAST:event_rbGautengActionPerformed

/********************************************************************************
                Only select Free State
********************************************************************************/
    private void rbFreeStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFreeStateActionPerformed
        rbWesternCape.setSelected(false);
        rbKwaZuluNatal.setSelected(false);
        rbMpumalanga.setSelected(false);
        rbEasternCape.setSelected(false);
        rbLimpopo.setSelected(false);
        rbGauteng.setSelected(false);
        rbNorthernCape.setSelected(false);
        rbFreeState.setSelected(true);
        rbNorthWest.setSelected(false);
    }//GEN-LAST:event_rbFreeStateActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    //Clears any input from fields listed below:
    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtOutput.setText("");
        txtFirstName.setText(""); 
        txtSurname.setText("");
        txtAge.setText("");
        txtAddress.setText("");
        txtTraffic.setText("");
        
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        frmRegister frmRegister = new frmRegister();
        frmRegister.show();
        this.hide();
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnRegister;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblProvince;
    private javax.swing.JLabel lblSurname;
    private javax.swing.JLabel lblTrafficRegisterNumber;
    private javax.swing.JRadioButton rbEasternCape;
    private javax.swing.JRadioButton rbFreeState;
    private javax.swing.JRadioButton rbGauteng;
    private javax.swing.JRadioButton rbKwaZuluNatal;
    private javax.swing.JRadioButton rbLimpopo;
    private javax.swing.JRadioButton rbMpumalanga;
    private javax.swing.JRadioButton rbNorthWest;
    private javax.swing.JRadioButton rbNorthernCape;
    private javax.swing.JRadioButton rbWesternCape;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextArea txtOutput;
    private javax.swing.JTextField txtSurname;
    private javax.swing.JTextField txtTraffic;
    // End of variables declaration//GEN-END:variables
}
